title:
    default: "Ben Plummer | Freelance Web Developer based in Warwickshire"
    suffix: "Ben Plummer | Freelance Web Developer based in Warwickshire"
post:
    title:
        suffix: "Ben Plummer"
disqus:
    shortname: benplummer
